In [1]:
import numpy as np 
import tensorflow as tf 

from tensorflow import keras 
from tensorflow.keras import layers, Model, Input
from tensorflow.keras.layers import *

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])
arr3 = np.array([1,2,3,4,5,6])
labels = np.array([1,0,1,0,1,0])

In [3]:
inp1 = Input(shape = (1,), name = 'input1')
inp2 = Input(shape = (1,), name = 'input2')
inp3 = Input(shape = (1,), name = 'input3')

In [4]:
inp1 = Input(shape = (1,), name = 'input1')
inp2 = Input(shape = (1,), name = 'input2')
inp3 = Input(shape = (1,), name = 'input3')

conc = tf.keras.layers.Concatenate(axis = 1, name = 'concat_layer')([inp1, inp2, inp3])
d1 = Dense(3, activation = 'relu', name = 'd1_layer')(conc)
d2 = Dense(2, activation = 'relu', name = 'd2_layer')(d1)
d3 = Dense(1, activation = 'sigmoid', name = 'd3_layer')(d2)

toy_model = Model(inputs = [inp1, inp2, inp3], outputs = d3)

toy_model.compile(
    loss = 'MSE',
    optimizer = 'SGD'
    )

toy_model.fit([arr1, arr2, arr3],
              labels, 
              epochs = 3,
              verbose = 0)

In [5]:
print(toy_model.predict([np.array([1]),np.array([2]),np.array([3])]))

[[0.5]]


In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
import os 
# os.listdir('drive/MyDrive')
path = 'drive/MyDrive'

In [8]:
toy_model.save('drive/MyDrive/toy_model.h5')

In [9]:
toy2 = tf.keras.models.load_model('drive/MyDrive/toy_model.h5')
toy2

In [10]:
toy2.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input1 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 input2 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 input3 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 concat_layer (Concatenate)     (None, 3)            0           ['input1[0][0]',                 
                                                                  'input2[0][0]',             

In [11]:
print('toy2 predict',toy2.predict([np.array([1]),np.array([2]),np.array([3])]))
print('toy predict',toy_model([np.array([1]),np.array([2]),np.array([3])]))
print('toy2 out',toy2([np.array([1]),np.array([2]),np.array([3])]))

toy2 predict [[0.5]]
toy predict tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)
toy2 out tf.Tensor([[0.5]], shape=(1, 1), dtype=float32)


In [12]:
for layer in toy2.layers:
    print((layer.name), layer)

input1 <keras.engine.input_layer.InputLayer object at 0x7f6c9b3d5d50>
input2 <keras.engine.input_layer.InputLayer object at 0x7f6c97d4e810>
input3 <keras.engine.input_layer.InputLayer object at 0x7f6c9b3d5910>
concat_layer <keras.layers.merge.Concatenate object at 0x7f6c96525910>
d1_layer <keras.layers.core.dense.Dense object at 0x7f6c97d57d50>
d2_layer <keras.layers.core.dense.Dense object at 0x7f6c9650f490>
d3_layer <keras.layers.core.dense.Dense object at 0x7f6c97cfdb90>


In [13]:
toy2_out = toy2.output
print(toy2_out)
toy_final = Dense(1, activation='sigmoid')(toy2_out)
toy2_added = Model(inputs=toy2.input, outputs=toy_final)
toy2_added.compile(
    loss = 'MSE',
    optimizer = 'SGD'
    )

toy2_added.fit([arr1, arr2, arr3],
              labels, 
              epochs = 3,
              verbose = 0)

KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), name='d3_layer/Sigmoid:0', description="created by layer 'd3_layer'")


In [14]:
x = toy_model.layers[-2].output 

In [15]:
print(x)

KerasTensor(type_spec=TensorSpec(shape=(None, 2), dtype=tf.float32, name=None), name='d2_layer/Relu:0', description="created by layer 'd2_layer'")


In [16]:
toy3 = Model(inputs =toy_model.input, outputs= toy_model.layers[-2].output)

In [17]:
toy3.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input1 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 input2 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 input3 (InputLayer)            [(None, 1)]          0           []                               
                                                                                                  
 concat_layer (Concatenate)     (None, 3)            0           ['input1[0][0]',                 
                                                                  'input2[0][0]',           

In [18]:
toy3([np.array([1]),np.array([2]),np.array([3])])

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0., 0.]], dtype=float32)>